# Generated by Django 4.1 on 2022-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_address_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=100, verbose_name='사용자 주소'),
        ),
    ]
