# Generated by Django 4.1 on 2022-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='사용자 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avaliablity_days_time',
            field=models.TextField(blank=True, verbose_name='meet 가능 시간'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='사용자 이름'),
        ),
    ]
