# Generated by Django 4.1 on 2022-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_address_alter_user_avaliablity_days_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='사용자 주소'),
        ),
    ]
