# Generated by Django 4.1 on 2022-08-06 05:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WwmGroup',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, help_text='그룹 설명', max_length=100)),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField(default=datetime.date.today)),
                ('leader_email', models.CharField(max_length=30)),
                ('avaliablity_days_time', models.CharField(blank=True, max_length=9999)),
                ('point', models.CharField(blank=True, max_length=40)),
                ('url', models.URLField()),
                ('memebers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
