# Generated by Django 4.1 on 2022-08-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WwmGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupname", models.CharField(max_length=20)),
                (
                    "desc",
                    models.CharField(blank=True, help_text="그룹 설명", max_length=100),
                ),
                ("startdate", models.DateField(default=datetime.date.today)),
                ("enddate", models.DateField(default=datetime.date.today)),
                ("leader_email", models.CharField(max_length=30)),
                (
                    "avaliablity_days_time",
                    models.CharField(blank=True, max_length=9999),
                ),
                ("point", models.CharField(blank=True, max_length=40)),
                ("url", models.URLField(default="http://127.0.0.1:8000")),
            ],
        ),
    ]
