# Generated by Django 4.1 on 2022-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwmgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwmgroup',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000'),
        ),
    ]
