# Generated by Django 4.1 on 2022-08-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwmgroup", "0002_wwmgroup_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="wwmgroup", name="avaliablity_days_time",),
        migrations.RemoveField(model_name="wwmgroup", name="point",),
        migrations.RemoveField(model_name="wwmgroup", name="url",),
    ]
