# Generated by Django 4.1 on 2022-08-11 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwmgroup', '0003_remove_wwmgroup_avaliablity_days_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wwmgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='wwmgroup',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
