# Generated by Django 4.1 on 2022-08-11 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwmgroup', '0004_remove_wwmgroup_user_wwmgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwmgroup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
