# Generated by Django 4.0.5 on 2022-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwmgroup', '0005_alter_wwmgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wwmgroup',
            name='meeting_station',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wwmgroup',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
