# Generated by Django 4.1 on 2022-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwmgroup', '0006_wwmgroup_meeting_station_wwmgroup_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wwmgroup',
            name='wwmgroupurl',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
