# Generated by Django 4.1 on 2022-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwmgroup', '0007_wwmgroup_wwmgroupurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwmgroup',
            name='wwmgroupurl',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
