# Generated by Django 4.1 on 2022-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whenmeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
