# Generated by Django 4.1 on 2022-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whenmeet', '0002_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(),
        ),
    ]
